workflows:
  ios-release:
    name: iOS Release Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    working_directory: example
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        - ios_credentials
      vars:
        BUNDLE_ID: "iu.yunji.example.flutter"
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        APP_STORE_APP_ID: "0000000000"  # 替换为你的 App Store Connect App ID
    scripts:
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles --project ios/Runner.xcodeproj
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Install pods
        script: |
          cd ios
          find . -name "Podfile.lock" -delete
          pod install
      - name: Flutter build ipa
        script: |
          flutter build ipa --release \
            --build-name=1.0.0 \
            --build-number=$(($(app-store-connect get-latest-testflight-build-number "$APP_STORE_APP_ID" 2>/dev/null || echo 0) + 1)) \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - your-email@example.com  # 替换为你的邮箱
        notify:
          success: true
          failure: true
      # 如果要自动上传到 App Store Connect / TestFlight，取消以下注释：
      # app_store_connect:
      #   auth: integration
      #   submit_to_testflight: true

  ios-ad-hoc:
    name: iOS Ad Hoc Build (直接安装)
    max_build_duration: 60
    instance_type: mac_mini_m2
    working_directory: example
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        - ios_credentials
    scripts:
      - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files "iu.yunji.example.flutter" \
            --type IOS_APP_ADHOC \
            --create
          app-store-connect fetch-signing-files "iu.yunji.example.flutter.LiveKit-Broadcast-Extension" \
            --type IOS_APP_ADHOC \
            --create
      - name: Add certificates to keychain
        script: |
          keychain initialize
          keychain add-certificates
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles --project ios/Runner.xcodeproj
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Install pods
        script: |
          cd ios
          find . -name "Podfile.lock" -delete
          pod install
      - name: Flutter build ipa (ad hoc)
        script: |
          flutter build ipa --release \
            --build-name=1.0.0 \
            --build-number=$BUILD_NUMBER \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      email:
        recipients:
          - your-email@example.com  # 替换为你的邮箱
        notify:
          success: true
          failure: true
